### PR TITLE
Add pub-file-urls test

### PR DESCRIPTION
**Pull request by GJFR**
Add test for checking whether reading systems prevent access to file URL resources (#293, [spec](https://www.w3.org/TR/epub-rs-33/#confreq-rs-file-urls)).

Sanity check done for readings systems on MacOS (e.g. calibre, Apple Books, colibrio, EPUBReader). I also checked some outdated reading systems that are known to load file URL resources, where the test functioned correctly as well.

I will have access to Windows and Linux this evening or tomorrow, so I can test on these operating systems as well.

### CODE REVIEW

**Comment by GJFR** [comment]
Great, @iherman! Will prepend the requested URL for each iframe.

I'd be happy to update the test reports. However, as I currently don't have an Android smartphone at hand, I might not be able to test all reading systems.

Just a small question; next to the `true` and `false` test outcomes, there's also `null`. When should the latter be used?

**Comment by iherman** [comment]
> Great, @iherman! Will prepend the requested URL for each iframe.
> 
> I'd be happy to update the test reports. However, as I currently don't have an Android smartphone at hand, I might not be able to test all reading systems.
> 
> Just a small question; next to the `true` and `false` test outcomes, there's also `null`. When should the latter be used?

There are actually two extra possible outcomes beyond the obvious true/false:

- null : not yet tested
- "n/a" : non applicable for some reasons (e.g., reading systems that does not have side-loading would use that for your side-loading tests)

If you cannot test all the reading systems, do not worry about it. The original authors should actually do that. What is really important at this point that, hopefully, each of the new tests will have at least two positive test results (the more the merrier of course), because otherwise we would have to do something about the corresponding MUST statement if it is a MUST statement we are testing (if not, it is not really an issue).

**Comment by iherman** [comment]
Iforgot to say: the default is null, ie, if the test reference doesn't appear in the list. So if you cannot test, don't worry about adding anything to the respective file.

**Review by iherman — APPROVED** [review]
The final approval is contingent on having some implementation reports also filled in. At that point, I will be happy to merge.

**Comment by GJFR** [comment]
It's difficult to find reliable images that are by default available on any OS variant. I guess it's best to leave it out for now, and just check for access to the log files. Later on, the test could extended to look for other files (perhaps requiring the tester to create files on pre-defined paths).

I will be able to fill in the reports tonight or tomorrow, and complete this PR.

**Pull request merged**
